#!/bin/zsh -f
# Explore autojump directory history with FZF
# CD into selected directory

local dir
dir="$(autojump -s | sed -n '1,/^$/p' | grep -v '^$' | awk '{for (i=2; i<=NF; ++i) print $i;}' | fzf)" && cd "$dir"
