#!/bin/zsh -f
# Use Ranger as a filepicker, writing selection(s) to stdout

local -r fs=$(mktemp --suffix="ranger-files")
trap "rm -f '$fs'" SIGINT EXIT
ranger --choosefiles="$fs"

if [[ $# -gt 0 ]]; then
    if command -v $1 >/dev/null 2>&1; then
        cat "$fs" | xargs $@
    else
        print -u2 "Command '$1' not found"
        return -1
    fi
else
    cat "$fs"
fi
