#!/bin/zsh
# Settings for `pass` password store and extensions

export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
export PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS='[a-zA-Z0-9!@#$%^&(),.:=?_]'
export PASSWORD_STORE_GENERATED_LENGTH=25
export PASSWORD_STORE_CLIP_TIME=20
# export PASSWORD_STORE_KEY=
# export PASSWORD_STORE_SIGNING_KEY=
# export PASSWORD_STORE_GPG_OPTS=
# export PASSWORD_STORE_PASSWORD_STORE_UMASK=
# export PASSWORD_STORE_X_SELECTION=
# export PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS=
